---
title: "Assesment"
output: html_document
date: "2024-11-01"
---
# Pregnancy termination trend over 6 year period in light of contraceptives dispensation trends



AIMS:

1. To see if there is a national trend correlation between number of dispensed contraceptives (oral and devices)
2. To see if this trend is maintained within health boards
3. To see in deprived areas 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r Used packages}
library(tidyverse)
library(janitor) # cleaning data
library(gt) # tables
library(here) # directory structure (will be useful later)
library(vroom)
library(stringr)
```


```{r Contraceptives and columns of interest}

columns_needed_from_prescription <- c("BNFItemCode", "NumberOfPaidItems")

```


```{r Abortion data }
#data on abortion 2000-2023
abortion_data <- read_csv("https://www.opendata.nhs.scot/dataset/d684d4a5-f7ae-4a1a-ae8d-adf55304274e/resource/342f9627-dfdd-41f5-a27c-0a3c7bcb8672/download/residence_age_2023.csv") %>% 
  clean_names()
```

```{r}
health_boards <- read_csv("https://www.opendata.nhs.scot/dataset/9f942fdb-e59e-44f5-b534-d6e17229cc7b/resource/652ff726-e676-4a20-abda-435b98dd7bdc/download/hb14_hb19.csv") %>% 
  clean_names() %>% 
  select(hb, hb_name)
```


```{r URLs for prescription data}
#prescription data between 2018 and 2023 in a names vector

prescription_data_urls <- c(
  "dec_2023" = "https://www.opendata.nhs.scot/dataset/84393984-14e9-4b0d-a797-b288db64d088/resource/00cdf8d7-f784-4e87-894c-34f2540ea6ab/download/pitc202312.csv",
  "nov_2023" = "https://www.opendata.nhs.scot/dataset/84393984-14e9-4b0d-a797-b288db64d088/resource/21d11fed-a494-4e30-9bb6-46143c3b9530/download/pitc202311.csv",
  "oct_2023" = "https://www.opendata.nhs.scot/dataset/84393984-14e9-4b0d-a797-b288db64d088/resource/94134438-db1d-4b8d-8f70-5e9b0e47bd03/download/pitc202310.csv",
  "sep_2023" = "https://www.opendata.nhs.scot/dataset/84393984-14e9-4b0d-a797-b288db64d088/resource/2d3d240f-1467-4a91-9f0e-769745650cb9/download/pitc202309.csv",
  "aug_2023" = "https://www.opendata.nhs.scot/dataset/84393984-14e9-4b0d-a797-b288db64d088/resource/72ca4ad2-0228-4672-9eb0-cc911e4a8ca7/download/pitc202308.csv",
  "jul_2023" = "https://www.opendata.nhs.scot/dataset/84393984-14e9-4b0d-a797-b288db64d088/resource/7bb45ee6-6f1c-45f4-933b-958bdbe0ca4f/download/pitc202307.csv",
  "jun_2023" = "https://www.opendata.nhs.scot/dataset/84393984-14e9-4b0d-a797-b288db64d088/resource/66e9611a-fbea-45b2-9edd-351c388fd06d/download/pitc202306.csv",
  "may_2023" = "https://www.opendata.nhs.scot/dataset/84393984-14e9-4b0d-a797-b288db64d088/resource/a0cf1a9f-d8c3-4bda-a8d9-733897c4c288/download/pitc202305.csv",
  "apr_2023" = "https://www.opendata.nhs.scot/dataset/84393984-14e9-4b0d-a797-b288db64d088/resource/720699b0-7584-4ddb-9915-79b298189d1d/download/pitc202304.csv",
  "mar_2023" = "https://www.opendata.nhs.scot/dataset/84393984-14e9-4b0d-a797-b288db64d088/resource/8dd06c58-1a09-483a-8a01-5d68cfb8b38e/download/pitc202303.csv",
  "feb_2023" = "https://www.opendata.nhs.scot/dataset/84393984-14e9-4b0d-a797-b288db64d088/resource/ad6d7f4e-08fd-40ed-ad49-bf450d386f39/download/pitc202302.csv",
  "jan_2023" = "https://www.opendata.nhs.scot/dataset/84393984-14e9-4b0d-a797-b288db64d088/resource/6caa7144-f0e4-4ab0-b9e4-8fa10c8edf1c/download/pitc202301.csv",
  "jan_2022" = "https://www.opendata.nhs.scot/dataset/84393984-14e9-4b0d-a797-b288db64d088/resource/53a53d61-3b3b-4a12-888b-a788ce13db9c/download/pitc202201.csv",
  "feb_2022" = "https://www.opendata.nhs.scot/dataset/84393984-14e9-4b0d-a797-b288db64d088/resource/bd7aa5c9-d708-4d0b-9b28-a9d822c84e34/download/pitc202202.csv",
  "mar_2022" = "https://www.opendata.nhs.scot/dataset/84393984-14e9-4b0d-a797-b288db64d088/resource/a0ec3bf2-7339-413b-9c66-2891cfd7919f/download/pitc202203.csv",
  "apr_2022" = "https://www.opendata.nhs.scot/dataset/84393984-14e9-4b0d-a797-b288db64d088/resource/7de8c908-86f8-45ac-b6a4-e21d1df30584/download/pitc202204.csv",
  "may_2022" = "https://www.opendata.nhs.scot/dataset/84393984-14e9-4b0d-a797-b288db64d088/resource/1b4e3200-b6e6-415f-b19a-b9ef927db1ab/download/pitc202205.csv",
  "jun_2022" = "https://www.opendata.nhs.scot/dataset/84393984-14e9-4b0d-a797-b288db64d088/resource/debeadd8-2bbb-4dd3-82de-831531bab2cb/download/pitc202206.csv",
  "jul_2022" = "https://www.opendata.nhs.scot/dataset/84393984-14e9-4b0d-a797-b288db64d088/resource/26ce66f1-e7f2-4c71-9995-5dc65f76ecfb/download/pitc202207.csv",
  "aug_2022" = "https://www.opendata.nhs.scot/dataset/84393984-14e9-4b0d-a797-b288db64d088/resource/49fa5784-be06-4015-bc6d-9b5db8726473/download/pitc202208.csv",
  "sep_2022" = "https://www.opendata.nhs.scot/dataset/84393984-14e9-4b0d-a797-b288db64d088/resource/9d0a518d-9d9c-4bcb-afd8-51f6abb7edf1/download/pitc202209.csv",
  "oct_2022" = "https://www.opendata.nhs.scot/dataset/84393984-14e9-4b0d-a797-b288db64d088/resource/bd7bc2cf-4de5-4711-bd5a-9e3b77305453/download/pitc202210.csv",
  "nov_2022" = "https://www.opendata.nhs.scot/dataset/84393984-14e9-4b0d-a797-b288db64d088/resource/023986c0-3bb2-43cb-84e8-2e0b3bb1f55f/download/pitc202211.csv",
  "dec_2022" = "https://www.opendata.nhs.scot/dataset/84393984-14e9-4b0d-a797-b288db64d088/resource/00213ffa-941e-4389-9e6f-3bca8067da8c/download/pitc202212.csv",
  "jan_2021" = "https://www.opendata.nhs.scot/dataset/84393984-14e9-4b0d-a797-b288db64d088/resource/7722a6e6-a6b6-49ec-aa63-fdc4bc727f05/download/pitc202101.csv",
  "feb_2021" = "https://www.opendata.nhs.scot/dataset/84393984-14e9-4b0d-a797-b288db64d088/resource/3f5c55ac-1bcd-4c57-a7b6-12911f15239c/download/pitc202102.csv",
  "mar_2021" = "https://www.opendata.nhs.scot/dataset/84393984-14e9-4b0d-a797-b288db64d088/resource/df6fc708-5c50-4d57-a5c4-faa19a92c227/download/pitc202103.csv",
  "apr_2021" = "https://www.opendata.nhs.scot/dataset/84393984-14e9-4b0d-a797-b288db64d088/resource/51b7ad3f-6d52-4165-94f4-92e322656c85/download/pitc202104.csv",
  "may_2021" = "https://www.opendata.nhs.scot/dataset/84393984-14e9-4b0d-a797-b288db64d088/resource/167ffab7-a168-43d1-90c4-118aa955edfb/download/pitc202105.csv",
  "jun_2021" = "https://www.opendata.nhs.scot/dataset/84393984-14e9-4b0d-a797-b288db64d088/resource/05159d26-f504-47ce-9d33-29b739e666ea/download/pitc202106.csv",
  "jul_2021" = "https://www.opendata.nhs.scot/dataset/84393984-14e9-4b0d-a797-b288db64d088/resource/5c1cd207-1958-4105-923f-ab60983d3f90/download/pitc202107.csv",
  "aug_2021" = "https://www.opendata.nhs.scot/dataset/84393984-14e9-4b0d-a797-b288db64d088/resource/6cdae245-0423-4e6f-9e1c-dc9e129df3aa/download/pitc202108.csv",
  "sep_2021" = "https://www.opendata.nhs.scot/dataset/84393984-14e9-4b0d-a797-b288db64d088/resource/d7d1ada5-2763-4698-bf39-7bdb06f67377/download/pitc202109.csv",
  "oct_2021" = "https://www.opendata.nhs.scot/dataset/84393984-14e9-4b0d-a797-b288db64d088/resource/35cbc6b1-3462-4563-88ba-d57c03782534/download/pitc202110.csv",
  "nov_2021" = "https://www.opendata.nhs.scot/dataset/84393984-14e9-4b0d-a797-b288db64d088/resource/6ba23bd1-f53b-4946-bc79-00633239d08f/download/pitc202111.csv",
  "dec_2021" = "https://www.opendata.nhs.scot/dataset/84393984-14e9-4b0d-a797-b288db64d088/resource/ad9e7b46-47fb-4d42-baad-f8e98e8f5936/download/pitc202112.csv",
  "jan_2020" = "https://www.opendata.nhs.scot/dataset/84393984-14e9-4b0d-a797-b288db64d088/resource/e5c841f2-3e16-428b-97db-0798ec7a5fb4/download/pitc202001.csv",
  "feb_2020" = "https://www.opendata.nhs.scot/dataset/84393984-14e9-4b0d-a797-b288db64d088/resource/af121e7c-4124-4955-92e9-a9580ccd469e/download/pitc202002.csv",
  "mar_2020" = "https://www.opendata.nhs.scot/dataset/84393984-14e9-4b0d-a797-b288db64d088/resource/9581bd8d-5568-4462-93a6-6d7bfbbe7cbc/download/pitc202003.csv",
  "apr_2020" = "https://www.opendata.nhs.scot/dataset/84393984-14e9-4b0d-a797-b288db64d088/resource/9cdc0526-21ab-43de-b832-bc032cd31b24/download/pitc202004.csv",
  "may_2020" = "https://www.opendata.nhs.scot/dataset/84393984-14e9-4b0d-a797-b288db64d088/resource/f2ffa7b3-3f93-470a-8125-880afb9aafe0/download/pitc202005.csv",
  "jun_2020" = "https://www.opendata.nhs.scot/dataset/84393984-14e9-4b0d-a797-b288db64d088/resource/64131d22-ab47-43ff-9674-ebe8ed7edbd7/download/pitc202006.csv",
  "jul_2020" = "https://www.opendata.nhs.scot/dataset/84393984-14e9-4b0d-a797-b288db64d088/resource/80b6ddb1-f09b-4d76-9927-da1e118b01ff/download/pitc202007.csv",
  "aug_2020" = "https://www.opendata.nhs.scot/dataset/84393984-14e9-4b0d-a797-b288db64d088/resource/5fd5f56e-d1d2-4f22-b4f7-224fbd50dca3/download/pitc202008.csv",
  "sep_2020" = "https://www.opendata.nhs.scot/dataset/84393984-14e9-4b0d-a797-b288db64d088/resource/e1b0cfdd-d184-4ebc-bd93-f1a10d84ead0/download/pitc202009.csv",
  "oct_2020" = "https://www.opendata.nhs.scot/dataset/84393984-14e9-4b0d-a797-b288db64d088/resource/83bf4892-d246-41f8-a6ca-d44d18e2a2ca/download/pitc202010.csv",
  "nov_2020" = "https://www.opendata.nhs.scot/dataset/84393984-14e9-4b0d-a797-b288db64d088/resource/ab8aa642-2562-4abb-a360-5c5f9e7e349c/download/pitc202011.csv",
  "dec_2020" = "https://www.opendata.nhs.scot/dataset/84393984-14e9-4b0d-a797-b288db64d088/resource/0c033702-4d88-4f2d-989c-a709b1f4529e/download/pitc202012.csv",
  "jan_2019" = "https://www.opendata.nhs.scot/dataset/84393984-14e9-4b0d-a797-b288db64d088/resource/3bd6e3cc-b8b7-493b-b6aa-f9fcadbb05d2/download/pitc201901.csv",
  "feb_2019" = "https://www.opendata.nhs.scot/dataset/84393984-14e9-4b0d-a797-b288db64d088/resource/3729a5c8-787a-46e3-ab7d-feed9aa91b4e/download/pitc201902.csv",
  "mar_2019" = "https://www.opendata.nhs.scot/dataset/84393984-14e9-4b0d-a797-b288db64d088/resource/87b21840-beb8-40fd-bad8-579643bc8b8b/download/pitc201903.csv",
  "apr_2019" = "https://www.opendata.nhs.scot/dataset/84393984-14e9-4b0d-a797-b288db64d088/resource/02197246-5d98-4ba9-b25d-218ac9cd91e6/download/pitc201904.csv",
  "may_2019" = "https://www.opendata.nhs.scot/dataset/84393984-14e9-4b0d-a797-b288db64d088/resource/7479536b-0b95-43d6-9152-31bbd522e6b4/download/pitc201905.csv",
  "jun_2019" = "https://www.opendata.nhs.scot/dataset/84393984-14e9-4b0d-a797-b288db64d088/resource/6ea2f299-76bc-49cd-ab43-9228b601da5f/download/pitc201906.csv",
  "jul_2019" = "https://www.opendata.nhs.scot/dataset/84393984-14e9-4b0d-a797-b288db64d088/resource/6e3856e9-88cb-495a-8c8a-54b0460df950/download/pitc201907.csv",
  "aug_2019" = "https://www.opendata.nhs.scot/dataset/84393984-14e9-4b0d-a797-b288db64d088/resource/5c667230-4201-4a09-949d-3e6cc3a4ec19/download/pitc201908.csv",
  "sep_2019" = "https://www.opendata.nhs.scot/dataset/84393984-14e9-4b0d-a797-b288db64d088/resource/ab3c15a9-44da-4a85-bb7a-58a8ce11f3d8/download/pitc201909.csv",
  "oct_2019" = "https://www.opendata.nhs.scot/dataset/84393984-14e9-4b0d-a797-b288db64d088/resource/55d93898-5382-4a59-a42e-bbc68f48b217/download/pitc201910.csv",
  "nov_2019" = "https://www.opendata.nhs.scot/dataset/84393984-14e9-4b0d-a797-b288db64d088/resource/eeee4a8f-3439-425a-aacd-58e536da90a0/download/pitc201911.csv",
  "dec_2019" = "https://www.opendata.nhs.scot/dataset/84393984-14e9-4b0d-a797-b288db64d088/resource/fa276ad2-669a-472f-9c47-809f199fae21/download/pitc201912.csv",
  "jan_2018" = "https://www.opendata.nhs.scot/dataset/84393984-14e9-4b0d-a797-b288db64d088/resource/82ef2c55-5a31-4759-ab9a-83b176e107f2/download/pitc201801.csv",
  "feb_2018" = "https://www.opendata.nhs.scot/dataset/84393984-14e9-4b0d-a797-b288db64d088/resource/1ae16a5f-aa26-4911-989b-ba4a6ab87037/download/pitc201802.csv",
  "mar_2018" = "https://www.opendata.nhs.scot/dataset/84393984-14e9-4b0d-a797-b288db64d088/resource/0b7bc1dd-9731-405b-a55e-656a8c996a58/download/pitc201803.csv",
  "apr_2018" = "https://www.opendata.nhs.scot/dataset/84393984-14e9-4b0d-a797-b288db64d088/resource/e35aebd7-55be-4c8b-82b7-54d1ed946b91/download/pitc201804.csv",
  "may_2018" = "https://www.opendata.nhs.scot/dataset/84393984-14e9-4b0d-a797-b288db64d088/resource/a2a3d0fd-d9c4-48e9-a569-c5d8abdf76f0/download/pitc201805.csv",
  "jun_2018" = "https://www.opendata.nhs.scot/dataset/84393984-14e9-4b0d-a797-b288db64d088/resource/d73cfc66-3330-416f-8507-873db28eca5c/download/pitc201806.csv",
  "jul_2018" = "https://www.opendata.nhs.scot/dataset/84393984-14e9-4b0d-a797-b288db64d088/resource/fec5dfdb-96dc-4e87-b7a0-6ecf20ec86e9/download/pitc201807.csv",
  "aug_2018" = "https://www.opendata.nhs.scot/dataset/84393984-14e9-4b0d-a797-b288db64d088/resource/592f3b58-2da8-4cc7-b4ab-e0eb0f16aa3f/download/pitc201808.csv",
  "sep_2018" = "https://www.opendata.nhs.scot/dataset/84393984-14e9-4b0d-a797-b288db64d088/resource/bd18b099-942d-42fb-9fa5-b947714381cd/download/pitc201809.csv",
  "oct_2018" = "https://www.opendata.nhs.scot/dataset/84393984-14e9-4b0d-a797-b288db64d088/resource/37e94a73-121e-443e-9564-2e1d9e36c5eb/download/pitc201810.csv",
  "nov_2018" = "https://www.opendata.nhs.scot/dataset/84393984-14e9-4b0d-a797-b288db64d088/resource/9cc56231-f184-4e29-a5ef-e6080bc78e93/download/pitc201811.csv",
  "dec_2018" = "https://www.opendata.nhs.scot/dataset/84393984-14e9-4b0d-a797-b288db64d088/resource/c50ed972-34e8-4cd6-8d2e-349e875c3ffa/download/pitc201812.csv"

)
```


```{r}
read_and_clean <- function(url) {
  # vroom used as a faster function for reading delimited files
  # only columns with prescription drug name, health board, and number of items paid selected to make loading onto R more memory efficient
    #since older data files have health board column named HBT2014 while newer have is named HBT, any_of() is used to select only the ones that exist in the file being read
  data <- vroom(url, col_select = any_of(c(columns_needed_from_prescription, "HBT", "HBT2014")), skip_empty_rows = TRUE)
  
 
  #data filtered for contraceptives (including contraceptive devices) only (based on the BNF code)
  data_filtered <- data %>%
  filter(str_starts(BNFItemCode, "0703") | str_starts(BNFItemCode, "21040")) %>% 
    clean_names()
  colnames(data_filtered)[3] ="hb"

  
  # assign function used to create a value with the name of the url from named list and assign read preprocessed data to that variable
name <- names(prescription_data_urls)[which(prescription_data_urls == url)] 
assign(name, data_filtered, envir = .GlobalEnv) 
}

lapply(prescription_data_urls, read_and_clean)
```

```{r Combine all prescription datases}
#sum the number of items paid for by health board
add_year <- function(url) {
  name <- names(prescription_data_urls)[which(prescription_data_urls == url)] 
  data <- get(name) 
  data <- data %>% 
    add_column(year = as.numeric(str_extract_all(name, "\\d+")))
  
  
  object_name <- paste(name, "sum", sep = "_")
  assign(object_name, data, envir = .GlobalEnv) 
}


lapply(prescription_data_urls, add_year)

full_prescirption_dataset <- bind_rows(mget(paste(names(prescription_data_urls), "sum", sep = "_")))

```


```{r filter datasets to create long term and short term contraception datasets}
long_term_contraception <- full_prescirption_dataset %>% 
  filter(str_detect(bnf_item_code, "0703022P|0703023|210400002")) %>% 
  group_by(year) %>% 
  summarise(sum_of_contraceptive_items = sum(number_of_paid_items, na.rm = TRUE))

short_term_contraception <- full_prescirption_dataset %>% 
  filter(!str_detect(bnf_item_code, "0703022P|0703023|210400002")) %>% 
  group_by(year) %>% 
  summarise(sum_of_contraceptive_items = sum(number_of_paid_items, na.rm = TRUE))

```

## Contraceptives and pregnancy termination trends




```{r Extract information from prescription datasets}

plot_prescription_long_term <- long_term_contraception %>% 
  ggplot(aes(y = sum_of_contraceptive_items, x = year)) +
  labs(title = "plot_prescription_long_term") +
  geom_line() 
plot_prescription_long_term

plot_prescription_short_term <- short_term_contraception %>% 
  ggplot(aes(y = sum_of_contraceptive_items, x = year)) +
  labs(title = "plot_prescription_short_term") +
  geom_line() 
plot_prescription_short_term


plot_abortion <- abortion_data %>% 
  filter(age_group == "All Ages", as.numeric(yearof_termination) %in% c(2018:2023)) %>% 
  # group_by(yearof_termination) %>% 
  # summarise(number_of_terminations_per_year = sum(numberof_terminations, na.rm = TRUE)) %>% 
  ggplot(aes(y = numberof_terminations, x = yearof_termination)) +
  geom_line() +
  facet_wrap(~hbr)
plot_abortion
```

